#!/usr/bin/env python3
"""
ETL: OPC_EDU_2025.pdf → SQL INSERT for planteles table.
Usage:
  python3 backend/etl/carga_planteles.py temp/OPC_EDU_2025.pdf
  → outputs planteles_inserts.sql in temp/

Parses pdftotext -layout output. Deduplicates by CLAVE.
"""
import re, sys, subprocess, os

pdf_path = sys.argv[1] if len(sys.argv) > 1 else 'temp/OPC_EDU_2025.pdf'
r = subprocess.run(['pdftotext', '-layout', pdf_path, '-'], capture_output=True, text=True)
if r.returncode != 0:
    print(f"Error: {r.stderr}", file=sys.stderr); sys.exit(1)

lines = r.stdout.split('\n')

INST_MAP = {
    'CONALEP': 'CONALEP', 'DGETI': 'DGETI', 'I.P.N.': 'IPN', 'IPN': 'IPN',
    'UNAM': 'UNAM', 'COLEGIO DE BACHILLERES': 'COLBACH', 'COLBACH': 'COLBACH',
    'IEMS': 'IEMS', 'DGB': 'DGB', 'CECYTEM': 'CECyTEM', 'CBT': 'CBT',
    'COBAEM': 'COBAEM', 'TELEBACHILLERATO': 'Telebachillerato',
}

EDOMEX = {'TOLUCA','ECATEPEC','NEZAHUALCÓYOTL','NEZAHUALCOYOTL','NAUCALPAN',
    'TLALNEPANTLA','ATIZAPÁN','ATIZAPAN','CUAUTITLÁN','CUAUTITLAN',
    'CHIMALHUACÁN','CHIMALHUACAN','TEXCOCO','COACALCO','LA PAZ','NICOLÁS ROMERO'}

MAIN_RE = re.compile(
    r'^([\wÁÉÍÓÚáéíóúñÑüÜ /.\-]+?)  +(\d)  +([\wÁÉÍÓÚáéíóúñÑüÜ /.\-]{3,}?)  +([A-Z]\d{6})  +'
)

def clean(s):
    return re.sub(r'\s+', ' ', s).strip().rstrip(',;. ')

# Remove addres-like patterns from a string
def strip_addr(s):
    return re.sub(
        r'(,\s*)?(C\.P\.\s*\d+|Tel\.\s*[\d\-]+|Fax\s*[\d\-]+|[\w.]+@[\w.]+|Col\.\s*[A-ZÁÉÍÓÚ][\w\s]+|C\.P\.\s*\d+)',
        '', s, flags=re.I
    ).strip()

def esc(s):
    return s.replace("'", "''")[:200]

records = {}
prev_school = ''

for i in range(len(lines)):
    line = lines[i]
    m = MAIN_RE.match(line)

    if m:
        alcadia = m.group(1).strip().title()
        inst_text = m.group(3).strip()
        clave = m.group(4).strip()

        if clave in records:
            continue

        after = line[m.end():].strip()
        after_clean = strip_addr(after)

        subsistema = 'Otras'
        utxt = inst_text.upper()
        for k, v in INST_MAP.items():
            if k in utxt:
                subsistema = v
                break

        # Build name: use context school name + specialization
        nombre = after_clean
        if prev_school and not prev_school.startswith('Técnico') and subsistema != 'Otras':
            school_clean = strip_addr(prev_school)
            if len(school_clean) > len(after_clean):
                nombre = school_clean
                if after_clean and after_clean != school_clean and len(after_clean) > 3:
                    nombre += ' — ' + after_clean

        if not nombre or len(nombre) < 4:
            nombre = clave

        nombre = clean(nombre)
        if len(nombre) > 120:
            nombre = nombre[:117] + '...'

        # Collect address lines
        addr_parts = []
        j = i + 1
        while j < len(lines):
            nxt = lines[j]
            if MAIN_RE.match(nxt):
                break
            stripped = nxt.strip()
            if stripped and nxt.startswith(' ' * 6) and stripped != after:
                if not stripped.startswith('Técnico en') and not stripped.startswith('Modalidad'):
                    addr_parts.append(stripped)
            j += 1

        # Build address
        direccion = clean(' '.join(addr_parts))
        # Remove phone/email from addresses
        direccion = re.sub(r'Tel\.\s*[\d\-]+\s*,?\s*', '', direccion)
        direccion = re.sub(r'Fax\s*[\d\-]+\s*,?\s*', '', direccion)
        direccion = re.sub(r'[\w.]+@[\w.]+\s*', '', direccion)
        # Remove text that looks like name data
        direccion = re.sub(r'^CENTRO DE ESTUDIOS[\w\s]+?(?=Calle|Av\.|Carretera|Prol\.|Cda\.|Grutas|Manuel|Hacienda)', '', direccion)
        direccion = clean(direccion)
        if len(direccion) > 200:
            direccion = direccion[:197] + '...'

        alcadia_upper = alcadia.upper()
        estado = 'Estado de México' if alcadia_upper in EDOMEX else 'Ciudad de México'

        records[clave] = (clave, nombre, subsistema, alcadia, estado, direccion)

    stripped = line.strip()
    if any(stripped.startswith(p) for p in ['CENTRO DE', 'COLEGIO DE', 'ESCUELA', 'DIRECCIÓN']):
        prev_school = stripped
    if 'ALCALDÍA' in stripped and 'MUNICIPIO' in stripped:
        prev_school = ''

# Generate SQL
out_path = os.path.join(os.path.dirname(pdf_path), 'planteles_inserts.sql')
with open(out_path, 'w', encoding='utf-8') as f:
    f.write(f"-- Generated by carga_planteles.py from {os.path.basename(pdf_path)}\n")
    f.write(f"-- {len(records)} unique planteles loaded\n\n")
    f.write("USE ecoems_db;\n\n")
    f.write("TRUNCATE TABLE planteles;\n\n")
    f.write("INSERT INTO planteles (clave, nombre, subsistema, municipio, estado, direccion) VALUES\n")

    batch = list(records.values())
    for idx, rec in enumerate(batch):
        vals = [esc(v) for v in rec]
        comma = ',' if idx < len(batch) - 1 else ';'
        f.write(f"('{vals[0]}','{vals[1]}','{vals[2]}','{vals[3]}','{vals[4]}','{vals[5]}'){comma}\n")

print(f"✅ {len(records)} planteles → {out_path}")
