-- Generated by carga_planteles.py from OPC_EDU_2025.pdf
-- Filtered to subsistema in: IPN, UNAM
-- 31 unique planteles loaded

USE ecoems_db;

INSERT INTO planteles (clave, nombre, especialidad, subsistema, municipio, estado, direccion, latitud, longitud) VALUES
('I504100','(CECyT 4) "LÁZARO CÁRDENAS" RAMA DE INGENIERÍA Técnico en procesos industriales,','I.C.F.M.','IPN','Álvaro Obregón','Ciudad de México','01110','19.35819','-99.203135'),
('U601000','Y CIENCIAS FÍSICO-MATEMÁTICAS ESCUELA NACIONAL PREPARATORIA PLANTEL NÚM. 8 "MIGUEL E. SCHULZ"','','UNAM','Álvaro Obregón','Ciudad de México','Miranda, Col. Merced Gómez. C.P. 01600','19.359726','-99.212345'),
('I506200','(CECyT 6) "MIGUEL OTHÓN DE MENDIZÁBAL" RAMA DE enfermería, Técnico laboratorista','C.M.B.','IPN','Azcapotzalco','Ciudad de México','Av. Jardín y Calle 4 s/n, Col. Del Gas. C.P. 02950','19.482607','-99.186979'),
('I508100','(CECyT 8) "NARCISO BASSOLS" RAMA DE INGENIERÍA Y','','IPN','Azcapotzalco','Ciudad de México','I.C.F.M. Av. de las Granjas núm. 618, Col. Santo Tomás. C.P. 02020, plásticos, Técnico en sistemas, CIENCIAS FÍSICO-MATEMÁTICAS, automotrices','19.483905','-99.182853'),
('U602000','COLEGIO DE CIENCIAS Y HUMANIDADES, PLANTEL AZCAPOTZALCO','','UNAM','Azcapotzalco','Ciudad de México','C.P. 02020','19.484496','-99.183005'),
('I513300','(CECyT 13) "RICARDO FLORES MAGÓN" RAMA DE','','IPN','Coyoacán','Ciudad de México','C. S. y A. Av. Taxqueña 1620, Col. Paseos de Taxqueña. C.P. 04250, informática, Técnico en gastronomía,, CIENCIAS SOCIALES Y ADMINISTRATIVAS, Técnico en gestión de la, ciberseguridad, ESCUELA NACIONAL PREPARATORIA PLANTEL NÚM. 6','19.341541','-99.166197'),
('U603000','U603000','','UNAM','Coyoacán','Ciudad de México','Corina núm. 3, Col. Del Carmen. C.P. 04100, "ANTONIO CASO", Cataratas y Llanura s/n, Col. Jardines del Pedregal. C.P','19.333731','-99.160268'),
('U604000','COLEGIO DE CIENCIAS Y HUMANIDADES, PLANTEL SUR','','UNAM','Coyoacán','Ciudad de México','04500','19.341971','-99.158933'),
('I505300','(CECyT 5) "BENITO JUÁREZ " RAMA DE CIENCIAS   Técnico en contaduría, Técnico en','','IPN','Cuauhtémoc','Ciudad de México','C. S. y A. Calle Emilio Dondé núm. 1, Col. Centro. C.P. 06040','19.429441','-99.139176'),
('I512300','(CECyT 12) "JOSÉ MARÍA MORELOS" RAMA DE','contaduría, Técnico en informática,','IPN','Cuauhtémoc','Ciudad de México','C. S. y A., C.P. 06430','19.441032','-99.152517'),
('I501100','(CECyT 1) "GONZALO VÁZQUEZ VELA" RAMA DE','sistemas de control eléctrico, Técnico','IPN','Gustavo A. Madero','Ciudad de México','I.C.F.M. Av. 510, núm. 1000, Col. Ejidos de Aragón. C.P. 07480','19.4907','-99.104008'),
('I510100','(CECyT 10) "CARLOS VALLEJO MÁRQUEZ" RAMA DE   control de calidad, Técnico en','I.C.F.M.','IPN','Gustavo A. Madero','Ciudad de México','de Aragón. C.P. 07950','19.492909','-99.10204'),
('I517100','"WALTER CROSS BUCHANAN" RAMA DE INGENIERÍA Y constructivos asistidos por','','IPN','Gustavo A. Madero','Ciudad de México','I.C.F.M. Av. 661 s/n, Col. Unidad San Juan de Aragón. C.P. 07920','19.486949','-99.117142'),
('U605000','CIENCIAS FÍSICO-MATEMÁTICAS','','UNAM','Gustavo A. Madero','Ciudad de México','Av. Ing. Eduardo Molina núm. 1577., "JUSTO SIERRA"','19.48572','-99.10331'),
('U606000','ESCUELA NACIONAL PREPARATORIA PLANTEL NÚM. 9 "PEDRO DE ALBA"','','UNAM','Gustavo A. Madero','Ciudad de México','07300','19.49019','-99.103408'),
('U607000','COLEGIO DE CIENCIAS Y HUMANIDADES, PLANTEL VALLEJO','','UNAM','Gustavo A. Madero','Ciudad de México','C.P. 07760, CENTRO MULTIMODAL DE ESTUDIOS CIENTÍFICOS Y','19.494038','-99.117304'),
('U608000','ESCUELA NACIONAL PREPARATORIA PLANTEL NÚM. 2','','UNAM','Iztacalco','Ciudad de México','','19.386438','-99.088581'),
('I507100','(CECyT 7) "CUAUHTÉMOC" RAMA DE INGENIERÍA Y   Técnico en soldadura industrial,','I.C.F.M.','IPN','Iztapalapa','Ciudad de México','Aztahuacán. C.P. 09500','19.343189','-99.055838'),
('U609000','CIENCIAS FÍSICO-MATEMÁTICAS COLEGIO DE CIENCIAS Y HUMANIDADES, PLANTEL ORIENTE','','UNAM','Iztapalapa','Ciudad de México','C.P. 09210','19.344208','-99.044059'),
('I502100','(CECyT 2) "MIGUEL BERNARD" RAMA DE INGENIERÍA Y metalurgia, Técnico en sistemas','I.C.F.M.','IPN','Miguel Hidalgo','Ciudad de México','Sotelo. C.P. 11200','19.421086','-99.182344'),
('I509100','(CECyT 9) "JUAN DE DIOS BÁTIZ" RAMA DE INGENIERÍA sistemas digitales, Técnico en','I.C.F.M.','IPN','Miguel Hidalgo','Ciudad de México','Mar Mediterráneo 227, Col. Popotla. C.P. 11400','19.418688','-99.184681'),
('I511100','(CECyT 11) "WILFRIDO MASSIEU" RAMA DE INGENIERÍA Técnico en procesos industriales,','I.C.F.M.','IPN','Miguel Hidalgo','Ciudad de México','C.P. 11340','19.416611','-99.18531'),
('U611000','Y CIENCIAS FÍSICO-MATEMÁTICAS ESCUELA NACIONAL PREPARATORIA PLANTEL NÚM. 4','','UNAM','Miguel Hidalgo','Ciudad de México','','19.414755','-99.184401'),
('I515200','(CECyT 15) "DIÓDORO ANTÚNEZ ECHEGARAY" RAMA   laboratorista clínico, Técnico en','C.M.B.','IPN','Milpa Alta','Ciudad de México','C.P. 12100','19.185111','-99.03243'),
('U612000','ESCUELA NACIONAL PREPARATORIA PLANTEL NÚM. 5 "JOSÉ VASCONCELOS"','','UNAM','Tlalpan','Ciudad de México','14300, Calle Adolfo López Mateos 145 entre calle Adolfo López','19.284233','-99.181254'),
('I514300','(CECyT 14) "LUIS ENRIQUE ERRO" RAMA DE CIENCIAS informática, Técnico en mercadotecnia,','','IPN','','Ciudad de México','C. S. y A. Peluqueros y Orfebrería s/n, Col. Michoacana. C.P. 15240','19.395719','-99.099039'),
('U613000','SOCIALES Y ADMINISTRATIVAS VENUSTIANO','','UNAM','','Ciudad de México','Calz. de la Viga núm. 54, Col. Merced Balbuena. C.P. 15810','19.402422','-99.096246'),
('U614000','ESCUELA NACIONAL PREPARATORIA PLANTEL NÚM. 1 "GABINO BARREDA"','','UNAM','Xochimilco','Ciudad de México','Tepepan. C.P. 16020','19.252625','-99.086195'),
('I503100','(CECyT 3) "ESTANISLAO RAMÍREZ RUIZ" RAMA DE','I.C.F.M.','IPN','','Ciudad de México','','19.407443','-99.106159'),
('U615000','NAUCALPAN DE','','UNAM','','Ciudad de México','','19.393993','-99.09584'),
('I518100','(CECyT 19) "LEONA VICARIO" RAMA DE INGENIERÍA Y','','IPN','Tecámac','Ciudad de México','I.C.F.M. Bosques, Unidad Habitacional "Los Héroes" Tecámac. C.P., alimentos, Técnico en construcción','19.398483','-99.101068');
